# Generated by Django 4.0.3 on 2022-04-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Player',
        ),
    ]
