# Generated by Django 4.0.3 on 2022-04-06 13:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_customuser_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
