# Generated by Django 4.0.3 on 2022-04-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_eventplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
