# Generated by Django 4.0.3 on 2022-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
