# Generated by Django 4.0.3 on 2022-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
